title: Robots Reading the Internet So You Don't Have To
description: Automated summaries of stuff, shipped by a robot with no feelings.
baseurl: ""
url: "https://autogennews.github.io"

exclude:
  - README.md
  - .idea/
